name: Build Pull Requests

on:
  push:
   branches-ignore:
    - nightly

jobs:
  build:

    strategy:
      matrix:
        # ubuntu build not supported in paket.dependencies for repo builds,
        # need to add linux commands first
        os: [windows-latest, macos-latest]
      fail-fast: false # we have timing issues on some OS, so we want them all to run
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Restore tools
      run: dotnet tool restore
    - run: yarn global add vsce
    - name: Run Test
      run: dotnet run --project build -- -t Build