name: Release

on: 
  workflow_dispatch:
    inputs:
      username:
        description: Github username of the person triggering the release
        default: "Krzysztof-Cieslak"
        required: true
      email:
        description: Email of the person triggering the release
        default: "krzysztof_cieslak@windowslive.com"
        required: true

jobs:
  release:
    # this workflow is the same as the build workflow, up until artifact upload + publish
    runs-on: windows-latest # can be any, just picked windows

    steps:
    # manual triggers are detached HEADs, so we need to checkout the branch
    # to actually create + push a commit later on in the workflow
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: Restore tools
      run: dotnet tool restore
    - name: install VSCE globally
      run: dotnet fake build -t InstallVSCE
    - name: Run Test
      run: dotnet fake build -t BuildPackage
    - name: upload artifact package
      uses: actions/upload-artifact@v2
      with:
        name: ionide-fsharp-vscode-ext
        path: release/
    - name: Publish Release
      env:
        nuget-key: ${{ secrets.NUGET_KEY }}
        github-user: ${{ github.event.inputs.username }}
        github-pw: ${{ secrets.USER_TOKEN }}
        vsce-token: ${{ secrets.VSCE_TOKEN }}
        user-email: ${{ github.event.inputs.email }}
      run: dotnet fake build -t Release
    - name: Build OpenVsix package
      run: dotnet fake build -t BuildPackageOpenVsix
    - name: Publish to Open VSX Registry
      uses: HaaLeo/publish-vscode-extension@v0
      id: publishToOpenVSX
      with:
        packagePath: "./release"
        pat: ${{ secrets.OPEN_VSX_TOKEN }}